Repository LeeChangHyeong/igeo-mubwotna, pull requests merged in 2024-06, with the labels that each got.

#6 [2024/06/04] feat/user read >> User 클래스와 UserStatusEnum 생성 및 구현
  src/main/java/com/sparta/igeomubwotna/entity/User.java
  src/main/java/com/sparta/igeomubwotna/entity/UserStatusEnum.java
Labels: 🌟 feat

#11 [2024/06/05] feat/sign-up >> 회원가입 기능
  src/main/java/com/sparta/igeomubwotna/IgeoMubwotnaApplication.java
  src/main/java/com/sparta/igeomubwotna/config/WebSecurityConfig.java
  src/main/java/com/sparta/igeomubwotna/controller/UserController.java
  src/main/java/com/sparta/igeomubwotna/dto/Response.java
  src/main/java/com/sparta/igeomubwotna/dto/SignupRequestDto.java
  src/main/java/com/sparta/igeomubwotna/entity/User.java
  src/main/java/com/sparta/igeomubwotna/repository/UserRepository.java
  src/main/java/com/sparta/igeomubwotna/service/UserService.java
  src/main/resources/application.properties
Labels: 🌟 feat

#17 [2024/06/05] feat/user-read >> 프로필 조회 기능 구현
  src/main/java/com/sparta/igeomubwotna/controller/UserController.java
  src/main/java/com/sparta/igeomubwotna/dto/UserProfileDto.java
  src/main/java/com/sparta/igeomubwotna/entity/UserStatusEnum.java
  src/main/java/com/sparta/igeomubwotna/security/UserDetailsImpl.java
  src/main/java/com/sparta/igeomubwotna/service/UserService.java
Labels: 🌟 feat

#18 [2024/06/05] feat/sign-in >> 로그인 기능 구현 (리프레시 토큰 x)
  build.gradle
  src/main/java/com/sparta/igeomubwotna/controller/UserController.java
  src/main/java/com/sparta/igeomubwotna/dto/Response.java
  src/main/java/com/sparta/igeomubwotna/dto/SigninRequestDto.java
  src/main/java/com/sparta/igeomubwotna/jwt/JwtUtil.java
  src/main/java/com/sparta/igeomubwotna/service/UserService.java
Labels: 🌟 feat

#22 [2024/06/05] feat/like >> 좋아요 기능 구현
  api_test/like_test.http
  src/main/java/com/sparta/igeomubwotna/controller/LikeController.java
  src/main/java/com/sparta/igeomubwotna/entity/CommentLikes.java
  src/main/java/com/sparta/igeomubwotna/entity/Like.java
  src/main/java/com/sparta/igeomubwotna/entity/RecipeLikes.java
  src/main/java/com/sparta/igeomubwotna/repository/CommentLikesRepository.java
  src/main/java/com/sparta/igeomubwotna/repository/CommentRepository.java
  src/main/java/com/sparta/igeomubwotna/repository/LikeRepository.java
  src/main/java/com/sparta/igeomubwotna/repository/RecipeLikesRepository.java
  src/main/java/com/sparta/igeomubwotna/repository/RecipeRepository.java
  src/main/java/com/sparta/igeomubwotna/service/LikeService.java
Labels: 🌟 feat

#21 [2024/06/05] feat/user-modify >> 프로필 수정 기능 구현
  src/main/java/com/sparta/igeomubwotna/controller/UserController.java
  src/main/java/com/sparta/igeomubwotna/dto/UserUpdateRequestDto.java
  src/main/java/com/sparta/igeomubwotna/entity/User.java
  src/main/java/com/sparta/igeomubwotna/service/UserService.java
Labels: 🌟 feat

#24 [2024/06/06] feat/sign-in >> 사용자 인증을 도와주는 Filter 구현
  src/main/java/com/sparta/igeomubwotna/controller/UserController.java
  src/main/java/com/sparta/igeomubwotna/filter/AuthFilter.java
  src/main/java/com/sparta/igeomubwotna/jwt/JwtUtil.java
Labels: 🌟 feat

#27 [2024/06/07] feat/sign-in >> 현재 사용자의 정보 SecurityContext에 저장하여 주입 받을 수 있도록 구현
  src/main/java/com/sparta/igeomubwotna/config/WebSecurityConfig.java
  src/main/java/com/sparta/igeomubwotna/dto/LoginRequestDto.java
  src/main/java/com/sparta/igeomubwotna/dto/LoginResponseDto.java
  src/main/java/com/sparta/igeomubwotna/filter/AuthFilter.java
  src/main/java/com/sparta/igeomubwotna/filter/JwtAuthenticationFilter.java
  src/main/java/com/sparta/igeomubwotna/filter/JwtAuthorizationFilter.java
  src/main/java/com/sparta/igeomubwotna/security/UserDetailsImpl.java
  src/main/java/com/sparta/igeomubwotna/security/UserDetailsServiceImpl.java
  src/main/java/com/sparta/igeomubwotna/service/UserService.java
Labels: 🌟 feat

#29 [2024/06/07] feat/recipe add >> 레시피 추가, 단건 조회, 수정 기능 구현 (+삭제)
  src/main/java/com/sparta/igeomubwotna/controller/RecipeController.java
  src/main/java/com/sparta/igeomubwotna/dto/RecipeRequestDto.java
  src/main/java/com/sparta/igeomubwotna/dto/RecipeResponseDto.java
  src/main/java/com/sparta/igeomubwotna/entity/Recipe.java
  src/main/java/com/sparta/igeomubwotna/entity/User.java
  src/main/java/com/sparta/igeomubwotna/repository/RecipeRepository.java
  src/main/java/com/sparta/igeomubwotna/service/RecipeService.java
Labels: 🌟 feat

#28 [2024/06/06] Feat/comment create >> comment CRUD 구현
  src/main/java/com/sparta/igeomubwotna/controller/CommentController.java
  src/main/java/com/sparta/igeomubwotna/dto/CommentRequestDto.java
  src/main/java/com/sparta/igeomubwotna/dto/CommentResponseDto.java
  src/main/java/com/sparta/igeomubwotna/entity/Comment.java
  src/main/java/com/sparta/igeomubwotna/entity/Recipe.java
  src/main/java/com/sparta/igeomubwotna/repository/CommentRepository.java
  src/main/java/com/sparta/igeomubwotna/service/CommentService.java
  src/main/java/com/sparta/igeomubwotna/service/RecipeService.java
Labels: 🌟 feat

#36 [2024/06/05] feat/like >> 좋아요 숫자 조회 기능 구현
  src/main/java/com/sparta/igeomubwotna/repository/CommentLikesRepository.java
  src/main/java/com/sparta/igeomubwotna/repository/RecipeLikesRepository.java
  src/main/java/com/sparta/igeomubwotna/service/LikeService.java
Labels: 🌟 feat

#40 [2024/06/07] feat/user-withdraw >> 회원 탈퇴 기능 구현
  src/main/java/com/sparta/igeomubwotna/controller/UserController.java
  src/main/java/com/sparta/igeomubwotna/dto/PasswordDto.java
  src/main/java/com/sparta/igeomubwotna/entity/User.java
  src/main/java/com/sparta/igeomubwotna/service/UserService.java
Labels: 🌟 feat

#41 Feat/sign in
  src/main/java/com/sparta/igeomubwotna/config/SecurityConfig.java
  src/main/java/com/sparta/igeomubwotna/controller/UserController.java
  src/main/java/com/sparta/igeomubwotna/entity/User.java
  src/main/java/com/sparta/igeomubwotna/filter/JwtAuthenticationFilter.java
  src/main/java/com/sparta/igeomubwotna/filter/JwtAuthorizationFilter.java
  src/main/java/com/sparta/igeomubwotna/jwt/JwtUtil.java
  src/main/java/com/sparta/igeomubwotna/service/UserService.java
Labels: 👾 bug, 🌟 feat

#43 [2024/06/07] Feat/comment like >> 인가처리
  src/main/java/com/sparta/igeomubwotna/controller/CommentController.java
  src/main/java/com/sparta/igeomubwotna/entity/Comment.java
  src/main/java/com/sparta/igeomubwotna/service/CommentService.java
Labels: 🌟 feat

#46 [2024/06/07] feat/sigin-in >> 토큰 인식 못하는 오류, 만료된 토큰 재발급
  src/main/java/com/sparta/igeomubwotna/config/SecurityConfig.java
  src/main/java/com/sparta/igeomubwotna/controller/UserController.java
  src/main/java/com/sparta/igeomubwotna/filter/JwtAuthenticationFilter.java
  src/main/java/com/sparta/igeomubwotna/filter/JwtAuthorizationFilter.java
  src/main/java/com/sparta/igeomubwotna/jwt/JwtUtil.java
Labels: 👾 bug, 🌟 feat

#48 [2024/06/07] feat/like >> Like 기능 관련 오류들 해결
  src/main/java/com/sparta/igeomubwotna/controller/LikeController.java
  src/main/java/com/sparta/igeomubwotna/entity/Comment.java
  src/main/java/com/sparta/igeomubwotna/entity/Recipe.java
  src/main/java/com/sparta/igeomubwotna/repository/CommentLikesRepository.java
  src/main/java/com/sparta/igeomubwotna/service/LikeService.java
Labels: 👾 bug

#50 [2024/06/07] feat/like >> Like 기능 로직 변경
  src/main/java/com/sparta/igeomubwotna/repository/CommentLikesRepository.java
  src/main/java/com/sparta/igeomubwotna/repository/RecipeLikesRepository.java
  src/main/java/com/sparta/igeomubwotna/service/CommentService.java
  src/main/java/com/sparta/igeomubwotna/service/LikeService.java
Labels: 🌟 feat

#51 [2024/06/10] Feat/recipe read >> 레시피 전체 조회 기능 구현
  src/main/java/com/sparta/igeomubwotna/controller/LikeController.java
  src/main/java/com/sparta/igeomubwotna/controller/RecipeController.java
  src/main/java/com/sparta/igeomubwotna/dto/RecipeResponseDto.java
  src/main/java/com/sparta/igeomubwotna/entity/Recipe.java
  src/main/java/com/sparta/igeomubwotna/repository/RecipeRepository.java
  src/main/java/com/sparta/igeomubwotna/service/RecipeService.java
Labels: 🌟 feat

#56 [2024/06/10] feat/like >> CommentLike 기능 관련 오류들 해결
  src/main/java/com/sparta/igeomubwotna/controller/LikeController.java
  src/main/java/com/sparta/igeomubwotna/service/LikeService.java
Labels: 👾 bug

#53 [2024/06/10] Feat/comment fix >> comment 관련 코드 리팩토링
  src/main/java/com/sparta/igeomubwotna/controller/CommentController.java
  src/main/java/com/sparta/igeomubwotna/dto/CommentRequestDto.java
  src/main/java/com/sparta/igeomubwotna/dto/CommentResponseDto.java
  src/main/java/com/sparta/igeomubwotna/entity/Comment.java
  src/main/java/com/sparta/igeomubwotna/service/CommentService.java
Labels: ♻️ refactor

#57 [2024/06/10] feat/sign-in >> 리프레시 토큰 오류 수정
  src/main/java/com/sparta/igeomubwotna/filter/JwtAuthenticationFilter.java
  src/main/java/com/sparta/igeomubwotna/filter/JwtAuthorizationFilter.java
  src/main/java/com/sparta/igeomubwotna/jwt/JwtUtil.java
Labels: 👾 bug

#59 [2024/06/10] Feat/recipe read >> Recipe 리팩토링
  src/main/java/com/sparta/igeomubwotna/controller/RecipeController.java
  src/main/java/com/sparta/igeomubwotna/service/RecipeService.java
Labels: ♻️ refactor

#60 [2024/06/07] feat/user-logout >> 로그아웃 기능 적용
  src/main/java/com/sparta/igeomubwotna/controller/UserController.java
  src/main/java/com/sparta/igeomubwotna/filter/JwtAuthorizationFilter.java
  src/main/java/com/sparta/igeomubwotna/service/UserService.java
Labels: 🌟 feat

#61 [2024/06/10] feat/swagger >> Swagger 연결
  build.gradle
  src/main/java/com/sparta/igeomubwotna/config/SecurityConfig.java
  src/main/java/com/sparta/igeomubwotna/controller/CommentController.java
  src/main/java/com/sparta/igeomubwotna/controller/LikeController.java
  src/main/java/com/sparta/igeomubwotna/controller/RecipeController.java
  src/main/java/com/sparta/igeomubwotna/controller/UserController.java
  src/main/java/com/sparta/igeomubwotna/filter/JwtAuthorizationFilter.java
Labels: 👾 bug, 🌟 feat
